server:
 port: 9002
 error:
  whitelabel:
   enabled: true
 servlet:
   context-path: /studentManagement


spring:
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   

 datasource:
  url: jdbc:mysql://localhost:3306/student_management_springboot
  username: root
  password: Mysql@#12345
  driver-class-name: com.mysql.cj.jdbc.Driver
 mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  

